import type { Prompt } from './types';

export const SNAPSHOT_PROMPTS: Prompt[] = [
  // --- Individual Female Prompts ---
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A close-up portrait of a woman with a gentle smile, her hair softly illuminated by the golden hour sun. The strong backlight creates a dreamy lens flare and a warm, hazy glow around her. The background is a soft-focus park scene. The image has the warm, delicate tones and noticeable grain of Kodak Portra 400 film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A dreamy portrait of a woman standing in a field at sunset. She is strongly backlit by the golden hour sun, which creates a hazy lens flare and a glowing halo effect around her hair. The background is softly blurred. The photo has the overexposed, pastel look of Fuji Pro 400H film, with visible, heavy grain and a slightly yellowish tint.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A playful, candid portrait of a woman with her eyes closed and a wide smile, as she tosses fresh, powdery snow into the air. The focus is on her happy expression, with the snowy background beautifully blurred. The soft light of an overcast winter day creates a dreamy, ethereal feel. The image has the gentle, pastel tones and fine grain of Fuji Pro 400H film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A playful portrait of a woman gently blowing snowflakes from her hands towards the camera. The background is a beautifully blurred, snow-covered park. The lighting is soft and even from the overcast sky, creating a dreamy, slightly overexposed look with a noticeable haze. The image has a nostalgic, faded memory quality with visible grain, reminiscent of vintage film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A woman is laughing, looking back over her shoulder in a field of wildflowers at sunset. The setting sun creates a beautiful halo effect in her hair and a warm, hazy lens flare. The shot is a medium close-up, capturing her joyful expression with a shallow depth of field. The photo has the dreamy look and grainy texture of Fuji Pro 400H film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A candid portrait of a woman smiling brightly on a city street at night. The background is filled with beautifully blurred city lights, creating a vibrant bokeh effect. The lighting is warm and flattering, capturing a joyful, spontaneous moment. The image has the feel of a vintage 50mm f/1.4 lens, with a gentle, dreamy glow and soft, imperfect focus.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A moody, cinematic portrait of a woman during a gentle winter snowfall at night. Soft, diffused light illuminates her face as snowflakes settle on her hair. The background is a dark, soft-focus park. Shot with an 85mm f/1.8 lens for a shallow depth of field and noticeable film grain, creating a peaceful and magical mood.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman in a cozy sweater looking back over her shoulder with a smile, in a charming village with wooden chalets and snow-capped mountains in the soft-focus background. The bright, crisp mountain air and sunshine create a fresh, happy mood. Shot on Kodak Portra 400 for its beautiful, natural skin tones, with a distinct fine grain and a warm, hazy glow.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A soft, intimate portrait of a woman sitting by a large cafe window on a rainy day. Soft, natural light illuminates her face. The image has a noticeable film grain, a warm yellowish tint, and a muted film look, capturing a thoughtful expression with the window and rain softly blurred into a dreamy haze behind her.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A candid shot of a woman in a vintage-style flower shop, smelling a bouquet of flowers. The scene is slightly overexposed from the light coming through the front window, giving it a soft, hazy filter effect and a blurred background. The colors are warm and desaturated, with a heavy grain, reminiscent of old Kodak Gold 200 film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman looking directly at the camera with a surprised or playful expression at night. The photo is taken with a harsh, direct flash, creating the Y2K digital camera aesthetic with blown-out highlights and deep shadows. The background is dark and out of focus. The mood is spontaneous and energetic, with a slightly blurry, imperfect quality.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A soft close-up portrait of a woman, backlit by the setting sun in a park. The strong backlight creates a beautiful lens flare and a warm, hazy glow that envelops her. The background is softly out of focus. The image is graded with pastel colors, noticeable grain, and emulates the soft, delicate look of Fujifilm film.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A woman in a vibrant red dress walking down a charming, sunlit European cobblestone street, looking back at the camera with a bright smile. The background is a soft-focus blur of old buildings and outdoor cafe seating. Shot on Kodak Portra 400 for its warm, beautiful colors, with a noticeable fine grain.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A woman standing in a vast green field at dusk, with mountains in the soft-focus background under a pastel-colored sky. The lighting is soft and atmospheric. The image has a grainy, nostalgic film quality with muted tones, capturing a serene and contemplative moment.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A classic black and white portrait of a woman in a simple white dress, standing in a park with a soft-focus background of trees. The lighting creates a gentle contrast, highlighting her thoughtful expression. The image has the timeless quality and distinct grain of Ilford HP5 film.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A black and white photo of a woman waiting on a city street at night. She looks pensively into the distance, with the blurred lights of traffic creating a beautiful bokeh effect in the background. The mood is cinematic and lonely, with heavy grain and soft focus.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A joyful, energetic portrait of a woman in a school uniform running and splashing in the ocean waves at the beach. Her hair is flying, and she has a huge smile. The image has a bright, slightly overexposed, and hazy look with the vibrant, cool tones of Japanese youth films, complete with visible film grain.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman in a flowing white dress in a lush green tea field in Jeju. The shot is a medium shot focusing on her, with rows of tea plants blurring into the background. The soft morning light creates a fresh, natural mood. Shot with a Fuji film aesthetic, with soft tones and fine grain.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A candid portrait of a woman sitting on a traditional Jeju stone wall, overlooking the ocean at sunset. The focus is on her, with the sea softly blurred behind. The warm golden hour light creates a nostalgic and peaceful atmosphere. The aesthetic is inspired by a Contax T3 film camera, known for its beautiful color rendition and slight vignetting.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A candid shot of a woman laughing as she's surrounded by a cloud of iridescent soap bubbles in a sun-drenched park. The strong backlight from the sun makes the bubbles glow. The image has a dreamy, magical quality with a soft-focus background and visible film grain. Shot on Kodak Portra 400 for its warm, vibrant colors.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman in a field of cherry blossoms in full bloom. The focus is on her soft smile, with the blossoms creating a beautiful, soft-focus background. The soft, diffused light of an overcast day creates a gentle, romantic mood. The image has the dreamy, pastel tones and grainy texture of Fuji Pro 400H film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A close-up portrait of a woman's joyful face illuminated by the warm glow of a sparkler she's holding. The background is a dark, blurry night. The image has significant film grain, a slightly soft focus, and a nostalgic, dreamy quality, captured as if on an old 35mm camera.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A pensive portrait of a woman in a school uniform, sitting on a concrete pier by the sea, listening to music with vintage-style headphones. She looks out towards the horizon. The soft, hazy light of a cloudy day creates a quiet, contemplative mood. The image has significant film grain and the desaturated, moody colors of a cinematic shot.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A pensive portrait of a woman looking out the window of a moving train. The city lights outside are streaked into long lines of color. Her reflection is faintly visible on the glass. The focus is on her expression. The mood is contemplative and cinematic, with the cool, moody tones and heavy grain of CineStill 800T film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A woman waits on an empty subway platform late at night, looking down the tracks. The approaching train's headlights create a dramatic lens flare, illuminating her from the side. The shot focuses on her, with the station's tiled walls blurring into the background. The mood is lonely and atmospheric, with the greenish, cinematic tones and grainy texture of film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A moody close-up portrait of a woman's face, illuminated by a soft blue light from the side. The background is dark and out of focus, creating an intimate and ethereal atmosphere with a cinematic feel, featuring soft focus and heavy grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman sitting in the shallow water of a sun-drenched pool. The bright sun reflects off the water's surface, creating sparkling highlights. The shot has a dreamy, hazy quality with the soft, vibrant colors of summer. Shot on Kodak Portra 400, with a noticeable grain and warm tint.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A candid, cheerful portrait of a woman with a genuine smile in a bustling urban alley. The background is a soft-focus blur of parked motorcycles and city textures. The image has a spontaneous, slice-of-life feel, with the warm, grainy look and slightly faded colors of vintage 35mm film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A retro-style portrait of a woman sitting on a tennis court, leaning against the net next to a vintage boombox. The bright sun creates a slightly hazy, nostalgic atmosphere. The image has the vibrant, slightly faded colors and soft blur of an old photograph.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "An intimate, quiet portrait of a woman partially hiding behind a sheer white curtain by a window. Soft, diffused daylight illuminates her face, creating a gentle and pensive mood. The background is a soft blur of green foliage outside. The image has a delicate, fine-grain film aesthetic with a dreamy haze.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A close-up portrait taken through a curtain of traditional wooden wind chimes at a temple. The focus is on the woman's serene expression, with the foreground chimes and background architecture softly blurred. Dappled sunlight creates a peaceful mood. Shot with a Fuji film aesthetic, featuring soft tones and a slight haze.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "An energetic, candid street style photo of a woman in the city, her hair looking damp as if caught in a sudden downpour. The focus is on her direct gaze, with the bustling city street blurred behind her. The image has a raw, in-the-moment feel with a grainy texture, reminiscent of a fashion magazine editorial.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A soft, warm portrait of a woman sitting indoors by a wooden window frame, holding an old-fashioned glass bottle. The gentle afternoon light creates a cozy, nostalgic atmosphere. The image has a grainy, vintage film aesthetic with muted, yellowish tones.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman in a school uniform and cozy winter coat, standing at a railroad crossing in a vast, snow-covered landscape. A train is softly blurred in the background. The bright, overcast light creates a clean, crisp atmosphere. The image has the quiet, cinematic feel of a Japanese film, with the muted tones and noticeable grain of Fuji Pro 400H.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A cinematic portrait of a woman on a pedestrian overpass above a busy highway at dusk. The wind gently blows through her hair. The cars below are a blur of motion and light trails. The photo has a contemplative, lonely mood with the cool, desaturated colors and heavy grain of film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A candid portrait of a woman lying on a picnic blanket in a grassy field, looking up at the camera with a playful smile. A woven basket is softly blurred beside her. The warm afternoon light creates a relaxed, dreamy atmosphere. Shot with a shallow depth of field, with the warm tones and fine grain of Kodak Portra 400.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A pensive portrait of a woman in a school uniform sitting on a rock by a tranquil river. She's looking towards the camera with a curious expression, one hand brushing her hair back. The soft, overcast light reflects gently off the water. The background is a soft-focus blur of green foliage. The image has the muted, gentle tones and visible grain of Fuji Pro 400H.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A spontaneous, motion-filled shot of a woman on a subway platform, turning back towards the camera with a joyful, windswept smile. Her hair is blurred by movement. The background is a long platform with station lights creating a beautiful bokeh. The mood is energetic and carefree, with the cinematic feel and grainy texture of a film still.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "An intimate portrait of a woman with blonde hair sitting on a tatami mat in a retro-style room. She's hugging her knees and looking at the camera with a soft smile. The warm, low light from an unseen source creates a cozy, nostalgic mood. An old TV and game console are softly blurred in the background. The image has a grainy, vintage film aesthetic with a distinct yellowish cast.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A quiet, close-up portrait of a woman looking out a bus window, resting her chin on her hands on the back of the seat in front. Her expression is gentle and contemplative. The world outside is a soft blur of motion and color. Shot with a shallow depth of field, capturing a moment of peaceful introspection. The colors have a soft, slightly desaturated film look with noticeable grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A striking portrait of a woman surrounded by lush green leaves and orange trumpet flowers. She is looking directly at the camera with a calm, mesmerizing gaze. The vibrant colors of the flowers frame her face. The lighting is soft and diffused, creating a rich, painterly quality with a slight, dreamy blur.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A refreshing portrait of a woman on a seawall on a bright sunny day. She is holding a bottle of a sports drink up towards the sky, her eyes closed, enjoying the sun. The sparkling blue ocean is a beautiful, soft-focus bokeh in the background. The image has a clean, high-key, and vibrant look, with a hazy, film-like quality reminiscent of a Japanese commercial.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A low-angle, dynamic shot of a woman with short hair, smiling joyfully as she reaches a can of soda towards a vast, clear blue sky. The composition is minimal and energetic, emphasizing freedom and happiness. The bright, direct sunlight creates a clean, high-contrast look with a hazy, nostalgic film glow.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman with braided pigtails looking out a window, her hand gently touching the glass. The focus is on her wistful expression, with sunlight creating bright, hazy reflections on the window pane. The world outside is a soft, sun-bleached blur. The mood is pensive and cinematic, with a warm, heavy grain film texture.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A candid, sun-drenched portrait of a woman sitting in a field and eating a slice of watermelon. She's looking at the camera with a playful gaze. The bright summer light creates a carefree and nostalgic atmosphere. The background of a bridge and city is softly blurred. Shot on Kodak Gold 200 for its warm, vibrant colors and distinct grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A whimsical portrait of a woman smiling with her eyes closed, using a giant lotus leaf as an umbrella in a gentle rain. The setting is a rocky stream, and the rain creates a soft, misty atmosphere. The lighting is diffused and ethereal. The mood is joyful and serene, with a slight blur and grainy film texture.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman standing by a railing, looking towards the camera with a bright smile, against the backdrop of a stunningly turquoise alpine lake and majestic green mountains. The focus is on her, with the grand scenery softly blurred. The bright, direct sunlight creates a vibrant, cheerful mood. Shot with the rich colors and fine grain of Kodak Ektar 100.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A soft, close-up portrait of a woman with a high ponytail, smiling gently at the camera while holding a can of a drink close to her cheek. The background is a soft-focus blur of green park foliage and bright sunlight. The lighting is bright and flattering, creating a fresh, K-drama style aesthetic with a hazy, film-like quality.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A candid shot of a woman lying on a tatami mat in front of an electric fan on a hot summer day. She has a relaxed, happy expression. Slices of watermelon are on a plate nearby. The warm, hazy light creates a nostalgic and lazy summer mood. The image has a grainy, slice-of-life film feel with a yellowish tint.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman with braided pigtails, smiling gently as she looks at the camera. She's standing by the water under a large bridge structure. The late afternoon sun casts a warm, golden light on her face. The water and bridge pillars create a beautiful, soft-focus background with a hazy, grainy film look.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A serene side-profile portrait of a woman with short hair, her eyes closed as she soaks in the bright sunlight. The background is a soft, dappled bokeh of green leaves. The strong light creates a beautiful rim light on her hair and skin. The mood is peaceful and contemplative, with a soft blur and film grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A moody, candid-style portrait of a woman in a bathroom, drying her wet hair with a striped towel held over her head. She's leaning against a tiled wall, looking away from the camera with a pensive expression. The lighting is soft and indirect, creating an intimate, unposed feel. The image has a raw, desaturated film aesthetic with heavy grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A serene underwater portrait of a woman with her eyes closed, floating peacefully. Sunlight filters through the water, casting beautiful, shimmering caustic light patterns across her face and body. Her hair drifts weightlessly around her. The mood is tranquil and dreamlike, with the rich blues of the water contrasting with the warm light. Shot on Kodak Portra 400 for its beautiful skin tones, vibrant colors, and noticeable grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "An ethereal underwater close-up of a woman's face, with small air bubbles rising from her lips. Her eyes are closed in a moment of bliss. The bright sun from above creates a beautiful, rippling light show on her skin. The background is a deep, tranquil blue. The image has a soft, dreamlike quality with a shallow depth of field and a slightly blurry, grainy texture, focusing on her peaceful expression.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A pensive portrait of a woman looking out a window on a cold day, her warm breath fogging the glass. Soft, natural light from outside illuminates her face, creating a gentle and intimate mood. The background is a soft blur of a winter scene outside. The image has a quiet, cinematic feel with muted tones and a noticeable fine-grain film texture.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A high-angle portrait of a woman lying down on a clean white surface, looking directly up at the camera with a calm expression. She is wearing a cozy scarf. The lighting is soft and even, creating a minimalist and serene mood. The image has a clean, airy feel with soft, pastel tones and a subtle film grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A cinematic portrait of a woman standing in front of a store with a bright red neon sign at night. The focus is on her, with the city street and passersby blurred by motion. The neon light casts a dramatic glow on her face. The mood is modern and slightly lonely, captured with the unique aesthetic and heavy grain of CineStill 800T film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A dreamy, ethereal portrait of a woman's profile surrounded by a blur of golden yellow flowers. The bright, diffused sunlight filters through the petals, creating a soft, warm glow and a beautiful bokeh effect. The mood is peaceful and serene. The image has a painterly quality with a heavy, hazy blur and a fine film grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "An intimate portrait of a woman seen through a window or reflection, looking down with a focused and gentle expression, perhaps at piano keys. Soft, warm indoor light creates a quiet, contemplative mood. The foreground has soft, blurry reflections, adding depth to the scene. The image has a delicate, fine-grain film aesthetic with a slightly desaturated color palette.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A low-angle portrait of a woman looking up with a hopeful expression towards pink flowers blooming above her. The background is a lush, soft-focus green. The bright, natural daylight creates a fresh and serene mood. Shot on Kodak Portra 400 for its beautiful, natural skin tones and vibrant colors, with a noticeable fine grain.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman in a white dress sitting on a sunny rooftop or balcony, looking at the camera with a gentle smile. The city buildings in the background are softly blurred. The bright, direct sunlight creates a nostalgic, summery feel. The image has the warm, slightly faded colors and distinct grain of vintage 35mm film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A playful, direct close-up portrait of a woman with curly black hair and rosy cheeks, looking straight at the camera while blowing a pink bubble with bubblegum. The background is a simple, plain mint green color. The lighting is bright and even, highlighting her features and the glossy bubble. The mood is fun and whimsical, with soft, pastel tones and a clean, high-fashion look.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'female',
    text: "A portrait of a woman with braided hair and a beret, looking back over her shoulder against a vast, clear blue sky. The bright sunlight creates a clean, high-key look. The composition is simple and striking, emphasizing a sense of freedom and youth. The image has the vibrant, cool tones and fine grain of a Japanese film aesthetic.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "An elegant close-up portrait of a woman with a delicate white lace veil covering her hair, looking at the camera with a soft, confident gaze. The background is a plain, neutral color. The lighting is soft and painterly, creating a timeless and romantic mood. The image has a fine-grain film texture with warm, rich tones.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'female',
    text: "A whimsical portrait of a woman with a white lace veil over her hair, playfully holding two bright red tomatoes. She looks to the side with a gentle smile. The background is a plain, neutral color. The lighting is soft and flattering, creating a quirky, storybook feel. The image has a warm, vintage film aesthetic with visible grain.",
  },

  // --- Individual Male Prompts ---
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A pensive man in a dimly lit coffee shop. The shot focuses on his expression, with steam rising from his cup and rain streaking down the window in the soft-focus background. Moody, atmospheric lighting with deep shadows. Shot on CineStill 800T for a cinematic feel, with heavy grain and a shallow depth of field.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A man on a London street, looking towards a classic red double-decker bus that is motion-blurred as it passes by, creating a dynamic and energetic scene. The focus is on the man's calm expression against the fast-moving city. The image has a cinematic, gritty film look with visible grain.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A man sitting on a wall overlooking the Eiffel Tower in Paris. The focus is on his relaxed posture, with the iconic landmark beautifully blurred in the background under a bright, partly cloudy sky. The image has the warm, pleasant tones and fine grain of Kodak Gold 200 film.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A man walking across a crosswalk on a historic European street, with gothic architecture softly blurred in the background. The late afternoon sun casts long shadows, creating a dramatic, story-like atmosphere. The photo has a grainy texture and a warm, desaturated color palette.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A black and white portrait of a man looking thoughtfully into the distance on a city street at night. The background is a soft-focus bokeh of streetlights. The image has a classic, cinematic feel, with the heavy grain and deep blacks of Ilford HP5 Plus film.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A portrait of a man in a dense, misty Gotjawal forest in Jeju. Dappled sunlight filters through the canopy, creating a gentle light on his face. The background is a soft-focus blur of lush green foliage. The mood is serene and ethereal, captured with a Fujifilm film aesthetic, with visible grain and a dreamy haze.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A candid portrait of a man at a rustic wooden table in a sunlit cafe. Natural light from a window creates soft shadows on his face. The background is softly blurred. Shot on Kodak Portra 400 film for its beautiful, natural skin tones and fine grain, with a warm, slightly yellowish tint.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A retro film portrait of a man in a cozy record shop, wearing headphones. The focus is on his face as he browses vinyls, with the records blurring into the background. The image features muted warm colors, soft grain, and a nostalgic atmosphere with a hazy glow, captured as if on 35mm film.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A portrait of a man walking along a secluded Jeju beach under an overcast sky. The focus is on him, with the dramatic clouds and sea creating a moody, soft-focus background. The composition is cinematic and contemplative, with a grainy, faded film look.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A high-contrast, black and white street style photo focusing on a man walking across a crosswalk. The shot is taken from a low angle, emphasizing his stride against a blurred city background. The sunlight creates harsh shadows, giving it a gritty, documentary feel. Shot on Ilford HP5 film for its classic, heavy grain structure.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A playful portrait of a man blowing a large soap bubble. The focus is on his face and the bubble, with his reflection captured on its surface. The background is a simple, out-of-focus green park. Soft, natural afternoon light illuminates his face. The image has the clean, airy look of Fuji Pro 400H, with a gentle blur and fine grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A man stands in a snowy forest at dusk. The cool, blue light of twilight fills the scene. The focus is on his introspective expression, his breath visible in the cold air. The background trees are soft and out of focus. The image has a cinematic, desaturated color grade with a subtle vignette and heavy film grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A man stands at a viewpoint overlooking a vast turquoise alpine lake and mountains. He's looking out at the scenery, his back partially to the camera. The focus is on him against the softly blurred, epic landscape. The bright sunlight creates a sense of freedom and adventure. The photo has the clean, vibrant look of Kodak Portra 400, with a subtle grainy texture.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A portrait of a man against a backdrop of a massive fireworks display. The shot is a medium close-up, focusing on his illuminated face as he watches the sky. The fireworks are a vibrant, colorful blur behind him, giving the scene a dramatic, cinematic feel with a hazy, grainy quality.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A man waits on an empty subway platform late at night. The approaching train's headlights create a dramatic lens flare and illuminate his figure. The background is a blur of motion and station lights. The overall mood is lonely and atmospheric, with the cinematic tones and heavy grain of CineStill 800T film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A moody, intimate portrait of a man in a dimly lit room filled with vintage posters and a record player. He's leaning forward, lost in thought. The warm, soft light from a single lamp creates deep shadows and a nostalgic, cinematic atmosphere. Shot on CineStill 800T for its characteristic halation, color, and noticeable grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A portrait of a young man wearing headphones, standing on a pedestrian overpass at dusk. The city lights and traffic below are a soft, beautiful bokeh. The cool tones of twilight create a contemplative and slightly lonely mood. The image has a cinematic feel with a grainy texture, with the shallow depth of field of an 85mm lens.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A soft-focus portrait of a man looking over his shoulder amidst blooming cherry blossom trees. The gentle, overcast light creates a dreamy, ethereal mood. The background is a wash of pastel pinks and whites. The image has the delicate, slightly overexposed look and fine grain of Fuji Pro 400H film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A relaxed, sun-drenched portrait of a man sitting barefoot on a lush green lawn, looking at the camera with a gentle smile. The bright afternoon sun creates a warm, carefree atmosphere with a hazy glow. The background is softly blurred. Shot on Kodak Portra 400 for its vibrant, natural colors and visible grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A charming, candid shot of a man sitting on a traditional wooden porch, playfully interacting with a cat. The warm, inviting light from indoors spills out, creating a cozy and heartwarming scene. The background is a soft focus of the home's interior. The image has a slice-of-life feel, with the warmth and grain of Kodak Gold 200 film.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "An energetic, playful portrait of a man holding a water gun on a rocky Jeju beach. He's looking off-camera with a focused expression. The bright summer sun creates sparkling highlights on the water in the blurred background. The mood is fun and adventurous, with the vibrant colors and grainy texture of a summer day on film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A bright, windswept portrait of a man in a denim jacket, smiling as he looks out over a river with a city skyline in the hazy background. The strong backlight from the sun creates a beautiful rim light and a cheerful, optimistic mood. The shot has a fresh, airy feel with a dreamy blur and a shallow depth of field.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A quiet, intimate portrait of a man on a swing in an empty playground at night. The soft, ambient light from a nearby streetlamp illuminates his gentle smile. The background is dark and out of focus, creating a pensive and slightly mysterious mood. The photo has a soft grain and a cinematic quality with a hazy glow.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A candid portrait of a man sitting alone in a waiting area with green plastic chairs and a tiled wall. He looks directly at the camera with a neutral, contemplative expression. The soft, diffused light from a window creates a quiet, observational mood. The image has the muted tones and heavy grain of a documentary-style film photo.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A street style portrait of a man sitting on wide concrete steps in an urban setting. He's resting his chin on his hands, looking thoughtfully into the distance. The bright but indirect sunlight creates interesting shadows. The background of the staircase and buildings is softly blurred. Shot with a 35mm lens for a classic, storytelling feel with a grainy texture.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A close-up portrait of a man's face illuminated by the warm glow of a sparkler he's holding. He has a joyful expression, and the background is a dark, blurry night. The image has significant film grain, a soft focus, and a nostalgic, dreamy quality, captured as if on an old 35mm camera.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A contemplative portrait of a man looking out the window of a moving train at night. The city lights streak by in a colorful blur. His reflection is faintly visible on the glass. The focus is on his pensive expression. The mood is cinematic, with the cool, moody tones and heavy grain of CineStill 800T film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A candid shot of a man absorbed in a book in a quiet, sunlit library aisle. Rays of light filter through a large window, illuminating dust motes in the air. The shelves of books create a beautiful, repeating pattern in the soft-focus background. The mood is peaceful and intellectual, with the warm, gentle tones and fine grain of Kodak Portra 400.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A cinematic portrait of a man standing on a neon-lit city street at night. The focus is on his face, with the vibrant colors of the signs creating a beautiful, colorful bokeh in the background. The mood is modern and energetic, captured with the unique aesthetic and grainy texture of CineStill 800T film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A candid portrait of a man in a white shirt and cap, walking through a sun-dappled park. The focus is on his thoughtful profile, with the lush green background softly blurred. The late afternoon light creates a warm, gentle atmosphere. Shot with a 50mm f/1.8 lens for a natural, classic look with a slight, hazy quality.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A pensive portrait of a man standing at a snowy railroad crossing. The focus is on him, with the tracks stretching into a soft-focus, wintery background. The cool, desaturated tones and visible heavy film grain create a lonely, cinematic atmosphere.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A candid street style photo of a man laughing as he crosses a busy city street. The focus is on his genuine expression, with the motion of traffic and pedestrians creating a dynamic, blurred background. The lighting is bright and natural from an overcast sky, capturing an authentic urban moment with a grainy, imperfect film look.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A quiet, close-up portrait of a man looking out a bus window, resting his chin on his hands on the back of the seat in front. His expression is gentle and contemplative. The world outside is a soft blur of motion and color. Shot with a shallow depth of field, capturing a moment of peaceful introspection. The colors have a soft, slightly desaturated film look with noticeable grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A low-angle, dynamic shot of a man smiling joyfully as he reaches a can of soda towards a vast, clear blue sky. The composition is minimal and energetic, emphasizing freedom and happiness. The bright, direct sunlight creates a clean, high-contrast look with a nostalgic, hazy film quality.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A candid, sun-drenched portrait of a man sitting in a field and eating a slice of watermelon. He's looking at the camera with a playful gaze. The bright summer light creates a carefree and nostalgic atmosphere. The background of a bridge and city is softly blurred. Shot on Kodak Gold 200 for its warm, vibrant colors and distinct grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A serene underwater portrait of a man with his eyes closed, floating peacefully. Sunlight filters through the water, casting beautiful, shimmering caustic light patterns across his face and body. His hair drifts weightlessly around him. The mood is tranquil and dreamlike, with the rich blues of the water contrasting with the warm light. Shot on Kodak Portra 400 for its beautiful skin tones, vibrant colors, and noticeable grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "An ethereal underwater close-up of a man's face, with small air bubbles rising from his lips. His eyes are closed in a moment of bliss. The bright sun from above creates a beautiful, rippling light show on his skin. The background is a deep, tranquil blue. The image has a soft, dreamlike quality with a shallow depth of field and a slightly blurry, grainy texture, focusing on his peaceful expression.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A pensive portrait of a man looking out a window on a cold day, his warm breath fogging the glass. Soft, natural light from outside illuminates his face, creating a gentle and intimate mood. The background is a soft blur of a winter scene outside. The image has a quiet, cinematic feel with muted tones and a noticeable fine-grain film texture.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A high-angle portrait of a man lying down on a clean white surface, looking directly up at the camera with a calm expression. He is wearing a cozy sweater. The lighting is soft and even, creating a minimalist and serene mood. The image has a clean, airy feel with soft, pastel tones and a subtle film grain.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A cinematic portrait of a man standing in front of a store with a bright red neon sign at night. The focus is on him, with the city street and passersby blurred by motion. The neon light casts a dramatic glow on his face. The mood is modern and slightly lonely, captured with the unique aesthetic and heavy grain of CineStill 800T film.",
  },
  {
    category: 'film',
    type: 'individual',
    gender: 'male',
    text: "A dreamy, ethereal portrait of a man's profile surrounded by a blur of golden yellow flowers. The bright, diffused sunlight filters through the petals, creating a soft, warm glow and a beautiful bokeh effect. The mood is peaceful and serene. The image has a painterly quality with a heavy, hazy blur and a fine film grain.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "An intimate portrait of a man seen through a window or reflection, looking down with a focused and gentle expression. Soft, warm indoor light creates a quiet, contemplative mood. The foreground has soft, blurry reflections, adding depth to the scene. The image has a delicate, fine-grain film aesthetic with a slightly desaturated color palette.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A low-angle portrait of a man looking up with a hopeful expression towards flowers blooming above him. The background is a lush, soft-focus green. The bright, natural daylight creates a fresh and serene mood. Shot on Kodak Portra 400 for its beautiful, natural skin tones and vibrant colors, with a noticeable fine grain.",
  },
  {
    category: 'travel',
    type: 'individual',
    gender: 'male',
    text: "A portrait of a man in a simple shirt sitting on a sunny rooftop or balcony, looking at the camera with a gentle smile. The city buildings in the background are softly blurred. The bright, direct sunlight creates a nostalgic, summery feel. The image has the warm, slightly faded colors and distinct grain of vintage 35mm film.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A playful, direct close-up portrait of a man looking straight at the camera while blowing a bubble with bubblegum. The background is a simple, plain color. The lighting is bright and even, highlighting his features and the glossy bubble. The mood is fun and unconventional, with a clean, modern look.",
  },
  {
    category: 'daily',
    type: 'individual',
    gender: 'male',
    text: "A portrait of a man looking back over his shoulder against a vast, clear blue sky. The bright sunlight creates a clean, high-key look. The composition is simple and striking, emphasizing a sense of freedom and youth. The image has the vibrant, cool tones and fine grain of a Japanese film aesthetic.",
  },

  // --- Couple Prompts ---
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate close-up of a couple embracing in a heavy snowstorm at night. The shot is tightly framed on their faces, capturing a romantic moment. The only light source is a faint, warm glow, illuminating the large, falling snowflakes between them. The mood is intensely romantic and cinematic, with a dreamy soft focus and heavy film grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A couple huddles together under a single umbrella on a rainy city street at night. The shot is a close-up, focusing on their happy expressions. The background is a beautiful blur of colorful city lights and neon signs, reflecting on the wet pavement, creating a romantic and cinematic mood with a CineStill 800T film aesthetic, complete with halation and grain.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A romantic photo of a couple in London, looking at each other in front of a motion-blurred red double-decker bus. The fast movement of the bus contrasts with the couple's still, intimate moment. The urban setting is dynamic yet romantic. The photo has a cinematic feel with a slightly desaturated color palette and noticeable film grain.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A candid photo of a couple sitting on a ledge at the Trocadéro in Paris, with a clear view of the Eiffel Tower in the background. They are casually dressed, sharing a relaxed moment. The lighting is bright and sunny, creating a happy, travel-diary feel. Shot on film for a warm, nostalgic look with a slight haze.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A joyful photo of a couple laughing together on a classic Parisian street, with the Eiffel Tower visible in the soft-focus background. They are holding hands, captured in a moment of pure happiness. The architecture and streetlights create a romantic atmosphere. The image has the warm, delicate tones and fine grain of Kodak Portra 400.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A romantic portrait of a couple holding hands and walking in a park near the Eiffel Tower. They are looking at each other with loving smiles. The composition is classic and beautiful, with the iconic tower softly blurred in the background. The image has a dreamy, timeless quality with a grainy film texture.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "An energetic photo of a couple holding hands and smiling as they walk across a crosswalk on a charming European street. The background features beautiful old buildings and a cathedral spire in the distance. The mood is happy and carefree, capturing the joy of exploring a new city together. Shot with the warm tones and visible grain of 35mm film.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A close-up, emotional portrait of a romantic couple embracing by the ocean in Jeju at sunset. The focus is on their intimate expressions, with the crashing waves and sunset sky creating a moody, atmospheric blur in the background. The photo has a visible heavy film grain and a warm, faded tint, enhancing the romantic tone.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate shot of a couple cooking together in a sun-drenched kitchen, with flour dust in the air. They are laughing, lost in the moment. Soft, warm natural light comes from a window. Captured with a 50mm prime lens for a shallow depth of field, emulating the look of Portra 400 film with its characteristic grain and warm tones.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A candid film photo of a couple sharing a laugh on a quiet, sun-drenched street. The focus is on their interaction, with the background softly blurred. The atmosphere is playful and romantic, with soft natural light, vintage pastel tones, heavy retro film grain, and a warm, nostalgic mood.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A couple walks through a field of tall silver pampas grass in Jeju, backlit by the late afternoon sun, creating a beautiful golden rim light around them. The background is a dreamy, hazy blur. Shot on Fuji Pro 400H for its soft, airy tones and noticeable grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A playful, candid shot of a couple inside a 'Life Four Cuts' (인생네컷) photo booth, making funny faces. The focus is tight on them, capturing a fun and intimate moment. The lighting is bright from the flash, with saturated colors, slight blur, and a grainy texture reminiscent of a classic disposable camera photo.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A couple snuggles under a blanket on a couch. The focus is on their cozy, intimate moment, with Christmas tree lights twinkling and completely out of focus in the background, creating a beautiful bokeh effect. The image has a warm, hazy glow and a soft, grainy texture.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A romantic, backlit photo of a couple surrounded by floating soap bubbles at sunset. They are looking at each other and smiling. The golden hour light creates a beautiful, warm flare and makes the bubbles shimmer. The aesthetic is dreamy and ethereal, captured on film with a soft focus background and heavy grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A blurry, artistic shot of a couple kissing on a moving carousel at a carnival at night. The focus is on their silhouette. The colorful lights of the carnival are streaked into beautiful patterns due to the motion blur. The image feels energetic, dreamlike, and romantic. Shot with a slow shutter speed, resulting in a hazy, grainy image.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate, moody portrait of a couple looking into each other's eyes, standing against a tiled wall in a busy subway station. People are blurred in motion in the foreground and background, creating a sense of a private moment in a public space. The dim, atmospheric lighting creates a cinematic, urban feel. Shot on CineStill 800T for its characteristic glow, grain, and color.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A couple sits together on a moving subway car, sharing earbuds. The focus is on their connected, quiet moment. The interior of the car is dim, with the fluorescent lights creating a moody, cinematic atmosphere and a soft-focus background. Shot on CineStill 800T, capturing the unique colors and grainy texture of a bustling city.",
  },
   {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A romantic night portrait of a couple holding sparklers, their faces illuminated by the warm, flickering light. They are looking at each other with smiles. The background is completely dark and out of focus, creating an intimate and magical moment. The image has a heavy film grain, soft focus, and a dreamy, nostalgic feel.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A joyful portrait of a couple, with one playfully giving the other a piggyback ride in a sunlit park. The background is a soft blur of green trees and sunlight. The shot captures their laughter and connection, with the warm, happy colors and fine grain of Kodak Portra 400.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A silhouette of a couple holding hands, watching a massive fireworks display over a city skyline. The focus is their shape against the bright explosions, which illuminate them. The colors of the fireworks are vibrant but slightly desaturated, giving it a dramatic, cinematic feel with a hazy, grainy, film-like quality.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A candid shot of a couple playfully grocery shopping. One of them is sitting in the shopping cart while the other pushes it. The focus is on their laughing interaction, with the colorful aisle creating a blurred, vibrant background. The bright, even lighting gives the photo a clean and lighthearted feel, with a subtle grain and soft focus of a film camera.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A couple stands embracing on a pedestrian walkway on a bridge as a train speeds past in the soft-focus background. The motion of the train is blurred, creating a dynamic contrast with the still couple. The setting sun casts a warm, golden light on them. The mood is both epic and intimate, with a cinematic, hazy, and grainy quality.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A playful, sun-drenched portrait of a couple on a grassy hill. They're wearing sunglasses and casual white shirts, striking a fun, dynamic pose. The background is a soft blur of green trees under a bright blue sky. The image has a vibrant, modern feel, shot on Kodak Portra 400 for its brilliant colors and fine grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate, tight close-up of a couple about to kiss, framed against a vast, clear blue sky. The bright sunlight creates a clean, high-key look, highlighting their expressions. The composition is minimal and powerful, focusing solely on their romantic connection. The photo has the sharp, clean aesthetic but with the noticeable grain of Kodak Ektar 100 film.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A cinematic shot of a couple holding hands and looking at each other, standing at a railroad crossing as a train passes by in the soft-focus background. The scene is lush and green. The warm afternoon light creates a romantic, story-like atmosphere. The image has the nostalgic feel and grainy texture of a film still, shot on Kodak Gold 200.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A candid, story-telling shot of a person taking a photo of their partner with a vintage film camera in a hazy green field at sunrise. The soft morning light creates a dreamy, ethereal glow. The image has a warm, nostalgic feel with a shallow depth of field and heavy grain, captured as if on Fuji Pro 400H film.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A gentle, romantic portrait of a couple in a lush green field. The woman is crouching with a bouquet of wildflowers while the man stands over her, looking down with a caring expression. Soft, overcast light creates a tender mood. The background is a beautiful soft-focus blur of foliage. Shot on film for a timeless, gentle quality with a visible grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A cinematic shot of a couple in Japanese-style school uniforms with bicycles in a park during the golden hour. One is on the bike, looking back at the other. The warm, hazy sunlight filters through the trees, creating a nostalgic, movie-still atmosphere. The photo has the gentle, narrative quality and grainy texture of a still from a coming-of-age film.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate close-up of a couple sitting together on the grass. The woman is winking playfully at the camera while holding a bouquet of white flowers, leaning against her partner. The focus is sharp on their faces, with the green background softly blurred. The image captures a joyful, spontaneous moment with warm, natural lighting and a subtle film grain.",
  },
  {
    category: 'travel',
    type: 'couple',
    gender: 'unisex',
    text: "A relaxed portrait of a couple standing on the rocky shore of Jeju island at dusk. The woman is smiling with her arm outstretched towards the sea, while her partner looks on. The fading sun creates a soft, warm glow on the horizon. The background of the calm sea is softly out of focus. The mood is peaceful and romantic, with a grainy, film-like color palette.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A bright, clean, K-drama style close-up of a couple in school uniforms. They are smiling warmly at the camera as if taking a selfie. The background is a soft-focus blur of park greenery. The lighting is bright and flattering, capturing their youthful energy. The image has a fresh, polished look with a subtle, dreamy film haze.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A candid, close-up shot of a couple making playful, silly faces at the camera. One is gently squeezing the other's cheeks. They are wearing casual plaid shirts in a park setting. The background is a soft blur of trees, putting all the focus on their fun, spontaneous interaction. Shot on Kodak Gold 200 for a warm, nostalgic feel with a distinct grain.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A joyful, candid shot of a couple laughing together while sitting on old stone steps in a park. They are looking up, sharing a happy moment. The surrounding greenery is lush but softly blurred. The image captures a moment of pure happiness, with the warm and natural look of film, complete with a slight grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A moody, intimate indoor portrait of a couple relaxing on a dark leather sofa. The woman rests her head on her partner's lap, holding a lollipop. The scene is lit by a single warm lamp, creating deep shadows and a cozy, cinematic atmosphere. The image has a grainy, vintage film aesthetic with a warm, yellowish tint.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A joyful and unconventional wedding-style snap of a couple in a park. The woman wears a simple white dress and a veil, while the man is in a casual shirt. They are holding hands and running with big smiles. The background is a blur of green trees, capturing a moment of pure, spontaneous fun. The photo has a bright, airy feel with a dreamy, film-like blur.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A dynamic, candid shot of a couple running across a city crosswalk, holding hands and laughing. The woman is wearing a wedding dress paired with jeans, and the man is in a casual suit. The urban background of buildings is slightly blurred. The image captures a modern, energetic, and romantic moment with a cinematic feel and a grainy texture.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A clean, minimalist studio portrait of a couple holding hands against a solid turquoise background. They have gentle, happy expressions. The man is holding a small bouquet of red flowers. The lighting is bright and even, creating a modern, stylish look reminiscent of a fashion magazine shoot. Shot with a Contax T3 for its sharp details, unique color rendition, and subtle grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A high-key studio portrait of a couple dressed in all white, standing close together against a plain light gray background. They are holding hands and looking directly at the camera with serene expressions. The lighting is soft and flattering, creating a timeless and elegant mood. The image has a fine grain and the clean aesthetic of Ilford Delta 100, with a slightly soft focus.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate, 'slice-of-life' candid shot of a couple brushing their teeth together, seen through a reflection in a bathroom mirror. The focus is on their reflections, capturing a simple, shared daily routine. The lighting is soft and warm, creating a cozy and realistic atmosphere. The background is softly out of focus, with a grainy, imperfect quality.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A whimsical, sun-drenched portrait of a couple in a field of tall grass at golden hour. The woman is blowing soap bubbles while the man stands beside her holding a bouquet of sunflowers. The strong backlight creates a warm, hazy glow and makes the bubbles iridescent. The mood is dreamy and romantic, with the look of Kodak Portra 400 film, including its distinct grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A couple sits closely together on the edge of a bridge as a train blurs past in the background. The late afternoon sun casts a warm, golden light on them. The composition is cinematic, capturing a quiet, intimate moment against a dynamic, moving backdrop. The photo has a hazy, nostalgic film quality with heavy grain.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "An intimate close-up of a couple's faces illuminated by the bright glow of sparklers they are holding. They are nose-to-nose, about to kiss, with joyful expressions. The background is completely dark, creating a magical and intensely romantic moment. The photo is rich with film grain, has a soft focus, and a warm, dreamy quality.",
  },
  {
    category: 'film',
    type: 'couple',
    gender: 'unisex',
    text: "A romantic close-up of a couple, their faces close together and softly lit by the golden hour sun. A strong backlight creates a dreamy lens flare and a warm, hazy glow around them. The background is a soft-focus park scene. The image has the warm, delicate tones and noticeable grain of Kodak Portra 400 film.",
  },
  {
    category: 'daily',
    type: 'couple',
    gender: 'unisex',
    text: "A dynamic, candid shot of a couple crossing a city street, looking back at the camera with a playful expression. The urban background is a soft-focus blur of traffic and buildings. The shot captures a spontaneous, energetic moment with the crisp, vibrant look but grainy texture of modern film.",
  }
];